services:
  personalblog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Map port 80 in the container to port 5000 on the host
    depends_on:
      - mongodb
      - elasticsearch
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDbSettings__ConnectionString=mongodb://mongodb:27017
      - MongoDbSettings__DatabaseName=PersonalBlogDb
      - ElasticSearch__Uri=http://elasticsearch:9200
    networks:
      - dev-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - dev-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disable security for development purposes
    ports:
      - "9200:9200"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
